In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("C:/Users/DELL/Desktop/bank-full.csv",sep = ';')
df.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no

In [3]:
df[df.duplicated()==True]

Empty DataFrame
Columns: [age, job, marital, education, default, balance, housing, loan, contact, day, month, duration, campaign, pdays, previous, poutcome, y]
Index: []

In [4]:
df[df.isnull().values==True]

Empty DataFrame
Columns: [age, job, marital, education, default, balance, housing, loan, contact, day, month, duration, campaign, pdays, previous, poutcome, y]
Index: []

In [5]:
df = df.drop(['contact'],axis=1)
df = df.drop(['day'],axis=1)
df = df.drop(['month'],axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        45211 non-null  int64 
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64 
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   duration   45211 non-null  int64 
 9   campaign   45211 non-null  int64 
 10  pdays      45211 non-null  int64 
 11  previous   45211 non-null  int64 
 12  poutcome   45211 non-null  object
 13  y          45211 non-null  object
dtypes: int64(6), object(8)
memory usage: 4.8+ MB


In [6]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df_job = le.fit(df['job'])
df['job'] = df_job.transform(df['job'])

df_marital = le.fit(df['marital'])
df['marital'] = df_marital.transform(df['marital'])

df_education = le.fit(df['education'])
df['education'] = df_education.transform(df['education'])

df_default = le.fit(df['default'])
df['default'] = df_default.transform(df['default'])

df_housing = le.fit(df['housing'])
df['housing'] = df_housing.transform(df['housing'])

df_loan = le.fit(df['loan'])
df['loan'] = df_loan.transform(df['loan'])

df_poutcome = le.fit(df['poutcome'])
df['poutcome'] = df_poutcome.transform(df['poutcome'])

df_y = le.fit(df['y'])
df['y'] = df_y.transform(df['y'])

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  int32
 2   marital    45211 non-null  int32
 3   education  45211 non-null  int32
 4   default    45211 non-null  int32
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  int32
 7   loan       45211 non-null  int32
 8   duration   45211 non-null  int64
 9   campaign   45211 non-null  int64
 10  pdays      45211 non-null  int64
 11  previous   45211 non-null  int64
 12  poutcome   45211 non-null  int32
 13  y          45211 non-null  int32
dtypes: int32(8), int64(6)
memory usage: 3.4 MB


In [7]:
df.head()

age  job  marital  education  default  balance  housing  loan  duration  \
0   58    4        1          2        0     2143        1     0       261   
1   44    9        2          1        0       29        1     0       151   
2   33    2        1          1        0        2        1     1        76   
3   47    1        1          3        0     1506        1     0        92   
4   33   11        2          3        0        1        0     0       198   

   campaign  pdays  previous  poutcome  y  
0         1     -1         0         3  0  
1         1     -1         0         3  0  
2         1     -1         0         3  0  
3         1     -1         0         3  0  
4         1     -1         0         3  0

In [8]:
from sklearn import preprocessing

scaler = preprocessing.StandardScaler()
scaler.fit(df[['age','job','marital','education','balance','duration','campaign','pdays','previous','poutcome']])
df[['age','job','marital','education','balance','duration','campaign','pdays','previous','poutcome']] = scaler.transform(df[['age','job','marital','education','balance','duration','campaign','pdays','previous','poutcome']])

df.head()

age       job   marital  education  default   balance  housing  loan  \
0  1.606965 -0.103820 -0.275762   1.036362        0  0.256419        1     0   
1  0.288529  1.424008  1.368372  -0.300556        0 -0.437895        1     0   
2 -0.747384 -0.714951 -0.275762  -0.300556        0 -0.446762        1     1   
3  0.571051 -1.020516 -0.275762   2.373280        0  0.047205        1     0   
4 -0.747384  2.035139  1.368372   2.373280        0 -0.447091        0     0   

   duration  campaign     pdays  previous  poutcome  y  
0  0.011016 -0.569351 -0.411453  -0.25194  0.444898  0  
1 -0.416127 -0.569351 -0.411453  -0.25194  0.444898  0  
2 -0.707361 -0.569351 -0.411453  -0.25194  0.444898  0  
3 -0.645231 -0.569351 -0.411453  -0.25194  0.444898  0  
4 -0.233620 -0.569351 -0.411453  -0.25194  0.444898  0

In [9]:
X = df.loc[:,df.columns!='y']
y = df.loc[:,df.columns=='y']

from sklearn.model_selection import train_test_split

X_tr,X_ts,y_tr,y_ts = train_test_split(X,y)
X_tr.shape,X_ts.shape

((33908, 13), (11303, 13))

In [24]:
from sklearn.ensemble import RandomForestClassifier
rfc1 = RandomForestClassifier(n_estimators=100,max_features="log2")
from sklearn.model_selection import cross_val_score
cross_val_score(rfc1,X,y,scoring='accuracy',cv=10).mean()

0.8742555479216797

In [25]:
from sklearn.ensemble import RandomForestClassifier
rfc1 = RandomForestClassifier(n_estimators=100)
from sklearn.model_selection import cross_val_score
cross_val_score(rfc1,X,y,scoring='accuracy',cv=10).mean()

0.8748748897107127

In [26]:
from sklearn.ensemble import RandomForestClassifier
rfc1 = RandomForestClassifier(n_estimators=100,criterion="entropy")
from sklearn.model_selection import cross_val_score
cross_val_score(rfc1,X,y,scoring='accuracy',cv=10).mean()

0.8749413005169936

In [27]:
from sklearn.model_selection import GridSearchCV

parameters={'min_samples_split' : list(range(2,13,1)),
            'max_depth': list(range(2,15,1)),
            'min_samples_leaf':list(range(1,10,1))}

rfc = RandomForestClassifier(n_estimators=100,criterion="entropy")
gs = GridSearchCV(estimator=rfc, param_grid = parameters, scoring='accuracy',iid=False,cv=10,return_train_score=True)
gs.fit(X_tr, y_tr)
gs.best_params_, gs.best_score_

({'max_depth': 14, 'min_samples_leaf': 2, 'min_samples_split': 2},
 0.9012326486300279)

In [10]:
df1=np.array(df)

In [11]:
dataSet=df1
dataSet.dtype

dtype('float64')

In [41]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

class ZPL_RandomForest():

    def __init__(self, n_estimators=100, min_samples_split=2, min_samples_leaf=2, max_depth=14, max_features=4):

        self.n_estimators = n_estimators 
        self.min_samples_split = min_samples_split
        self.min_samples_leaf = min_samples_leaf   
        self.max_depth = max_depth  
        self.max_features = max_features 

        self.trees = []
 
        for _ in range(self.n_estimators):
            tree = DecisionTreeClassifier(min_samples_split=self.min_samples_split, min_samples_leaf=self.min_samples_leaf,max_depth=self.max_depth)
            self.trees.append(tree)

    def fit(self, X, Y):
        
        sub_sets = self.ZiZhuCaiYang(X, Y)#获取上一步生成的随机采样集
        n_features = X.shape[1] #读取X数据集的列，获取特征的数量

        for i in range(self.n_estimators):
            sub_X, sub_Y = sub_sets[i]#获取每一个采样集中的X，Y
            nx = np.random.choice(n_features, self.max_features, replace=True)
            #从大小为n_features的矩阵中，均匀地随机采样出max_features个样本，并且允许重复
            #例如如果总的特征数量为16，我们会在这16个特征中获得指定的max_features个样本
            sub_X = sub_X[:, nx]#新的数据集sub_X的特征数量为nx，也就是我们指定的max_features个
            self.trees[i].fit(sub_X, sub_Y)       #模型拟合
            self.trees[i].feature_indices= nx     #规定起始区间，相当于换行符

    def predict(self, X):
        y_preds = []
        for i in range(self.n_estimators):
            nx = self.trees[i].feature_indices #nx为每个决策树的特征数量
            sub_X = X[:, nx] #子集sub_X是采样集X中特征数量为nx的数据集
            y_pre = self.trees[i].predict(sub_X) #利用决策树进行预测
            y_preds.append(y_pre) #将预测结果添加到y_preds矩阵中
        y_preds = np.array(y_preds).T 
        print(y_preds)
        y_pred = []
        for y_p in y_preds:
            
            y_pred.append(np.bincount(y_p.astype('int')).argmax())
            #  y_p.astype('int')将原本的float类型数据转换int类型，因为毕竟预测结果只有0和1
            #  np.bincount(y_p.astype('int'))可以统计每个索引出现的次数，也就是说：如果有10棵树预测y为0，90棵树预测y为1，那么返回[10,90]
            #  .argmax返回了np.bincount(y_p.astype('int'))这个数据集中出现最多的那个值的索引，
                #也就是说，如果预测y的值为1的树的数量大于预测y的值为0的树的数量，那么返回1,这是bagging简单投票法原理。
                #像之前的例子：如果有10棵树预测y为0，90棵树预测y为1，通过这样的计算会最终返回1
            # 利用此过程，我们可以将多个决策树，采用bagging算法结合起来
            
        return y_pred

    def ZiZhuCaiYang(self, X, Y):

        m = X.shape[0] #获取行数→查看有多少条数据
        Y = Y.reshape(m, 1)

        X_Y = np.hstack((X, Y)) #把X，Y两个数据集合并
        np.random.shuffle(X_Y) #把合并后的X，Y再随机打乱

        data_sets = []
        for _ in range(self.n_estimators):
            nm = np.random.choice(m, m, replace=True) #从大小为m的矩阵中，均匀地随机采样出m个样本，并且允许重复
            New_X_Y = X_Y[nm, :] 
            New_X = New_X_Y[:, :-1]
            New_Y = New_X_Y[:, -1:]
            data_sets.append([New_X, New_Y])
        return data_sets


if __name__ == '__main__':
    
    X = dataSet[:,0:13]
    y = dataSet[:,13]

    X_train, X_test, y_train, y_test = train_test_split(X, y)
    print("X_train.shape:", X_train.shape)
    print("Y_train.shape:", y_train.shape)

    clf = ZPL_RandomForest(n_estimators=100)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    print("Accuracy:", accuracy)


X_train.shape: (33908, 13)
Y_train.shape: (33908,)
[[1. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Accuracy: 0.8794125453419446


In [18]:
X.shape[1]

13

In [89]:
y

array([0., 0., 0., ..., 1., 0., 0.])

In [23]:
X = dataSet[:,0:13]
y = dataSet[:,13]

X_train, X_test, y_train, y_test = train_test_split(X, y)
print("X_train.shape:", X_train.shape)
print("Y_train.shape:", y_train.shape)

rf = ZPL_RandomForest(n_estimators=100)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

X_train.shape: (33908, 13)
Y_train.shape: (33908,)
Accuracy: 0.8850747589135628


In [33]:
1 in y_pred

True